server:
  port: 9100
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/my-springsecurity?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
#spring:
#  resources:
#    static-locations: classpath:/static/
